server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/postgres
    username: postgres
    password: thanh@123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # create, validate, none
    show-sql: true  # Log SQL

jwt:
    secretKey: "LBRxxp6OUM5+ZVxWjZhzGCur/GY4eE7OIpPa8FGOmqbeR4TkVx/Usw6hXi/OwyXh"
